version: '3'
services:
  hive-server:
    image: apache/hive:4.0.0-beta-1
    container_name: hive
    env_file:
      - Dockerfile.hive
      - ./hadoop-hive.env
    environment:
      - HIVE_CONF_DIR=/opt/hive/conf
      - SERVICE_NAME=hiveserver2
    ports:
      - "10000:10000"
      - "10002:10002"    
    volumes:
      - ./consume_kafka.hql:/docker-entrypoint-initdb.d/consume_kafka.hql
    networks:
      - servera_cdcNetwork

  # python-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.python
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./app:/home/app
  #   networks:
  #     - servera_cdcNetwork

volumes:
  warehouse:
    driver: local

networks:
  servera_cdcNetwork:
    external: true