version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: sample_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - cdcNetwork

  #This producer is to test kafka 
  debezium-kafka-producer:
    build:
      context: .
      dockerfile: Dockerfile.debezium-kafka-producer
    depends_on:
      - mysql
      - kafka
    volumes:
      - ./connector/debezium-connector-mysql-1.7.1.Final.jar:/app/debezium-connector.jar
      - ./eventProducer/kafka-producer.py:/app/kafka-producer.py
      - ./eventProducer/debezium-events.json:/app/debezium-events.json
    networks:
      - cdcNetwork

  kafka:
    build:
      context: .
      dockerfile: Dockerfile.kafka
    ports:
      - "9092:9092"
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - cdcNetwork

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - cdcNetwork

 # Debezium MySQL Connector
  debezium-mysql-connector:
    image: debezium/connect:1.7
    container_name: debezium-mysql-connector
    env_file: ./mysql-connector.env
    restart: always
    depends_on:
      - mysql
      - kafka
    ports:
     - 8083:8083
    environment:
      - BOOTSTRAP_SERVERS=kafka:9093
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - ENABLE_DEBEZIUM_SCRIPTING='true'
    volumes:
      - ./connector/debezium-connector-mysql-1.7.1.Final.jar:/kafka/connectors/debezium-connector-mysql/debezium-connector-mysql.jar
    networks:
      - cdcNetwork
    
  debezium-ui:
    image: debezium/debezium-ui:1.7
    restart: always
    container_name: debezium-ui
    hostname: debezium-ui
    depends_on:
      - debezium-mysql-connector
    ports:
      - '8084:8084'
    environment:
      KAFKA_CONNECT_URIS: http://debezium-mysql-connector:8083
    networks:
      - cdcNetwork

networks:
  cdcNetwork:
    driver: bridge
